const quizData = [
  {
    id: "q1",
    question: "What is the capital of France?",
    options: [
      { text: "Paris" },
      { text: "London" },
      { text: "Berlin" },
      { text: "Madrid" },
    ],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q2",
    question: "Which planet is known as the Red Planet?",
    options: [
      { text: "Mars" },
      { text: "Venus" },
      { text: "Jupiter" },
      { text: "Saturn" },
    ],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q3",
    question: "What is the largest mammal on Earth?",
    options: [
      { text: "Blue Whale" },
      { text: "Elephant" },
      { text: "Giraffe" },
      { text: "Hippopotamus" },
    ],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q4",
    question: "Which gas do plants absorb from the atmosphere?",
    options: [
      { text: "Oxygen" },
      { text: "Carbon Dioxide" },
      { text: "Nitrogen" },
      { text: "Hydrogen" },
    ],
    answerIndex: 1,
    selectedIndex: null,
  },
  {
    id: "q5",
    question: "Who wrote the play 'Romeo and Juliet'?",
    options: [
      { text: "William Shakespeare" },
      { text: "Charles Dickens" },
      { text: "Jane Austen" },
      { text: "Leo Tolstoy" },
    ],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q6",
    question: "What is the largest organ in the human body?",
    options: [
      { text: "Liver" },
      { text: "Heart" },
      { text: "Skin" },
      { text: "Lung" },
    ],
    answerIndex: 2,
    selectedIndex: null,
  },
  {
    id: "q7",
    question: "Which country is known as the Land of the Rising Sun?",
    options: [
      { text: "China" },
      { text: "India" },
      { text: "Japan" },
      { text: "South Korea" },
    ],
    answerIndex: 2,
    selectedIndex: null,
  },
  {
    id: "q8",
    question: "What is the chemical symbol for gold?",
    options: [{ text: "Au" }, { text: "Ag" }, { text: "Fe" }, { text: "Cu" }],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q9",
    question: "Who painted the Mona Lisa?",
    options: [
      { text: "Leonardo da Vinci" },
      { text: "Pablo Picasso" },
      { text: "Vincent van Gogh" },
      { text: "Michelangelo" },
    ],
    answerIndex: 0,
    selectedIndex: null,
  },
  {
    id: "q10",
    question: "What is the tallest mountain in the world?",
    options: [
      { text: "Mount Kilimanjaro" },
      { text: "Mount Everest" },
      { text: "Mount McKinley" },
      { text: "Mount Fuji" },
    ],
    answerIndex: 1,
    selectedIndex: null,
  },
  {
    id: "q11",
    question: "Which gas is most abundant in the Earth's atmosphere?",
    options: [
      { text: "Oxygen" },
      { text: "Carbon Dioxide" },
      { text: "Nitrogen" },
      { text: "Hydrogen" },
    ],
    answerIndex: 2,
    selectedIndex: null,
  },
];
export default quizData;
